import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Stack, Typography } from "@mui/material";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo App By Anas ur Rehman",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Stack
            sx={{
              width: "50%",
              alignItems: "center",
              justifyContent: "center",
              background: "blue",
              borderRadius: "1rem",
              boxShadow:
                "rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px",
            }}
          >
            <Typography sx={{ color: "white", fontSize: "3rem" }}>
              My Todo App
            </Typography>

            {children}
          </Stack>
        </body>
      </html>
    </StoreProvider>
  );
}
